apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking
type: Opaque
stringData:
  db-password: "banking_secure_pass_2024"
  jwt-secret: "banking_jwt_secret_key_production"
  internal-api-key: "internal_secret_key_production"
